language: go
cache:
  directories:
    - ${GOPATH}/pkg
    - ${GOPATH}/src
    - ${HOME}/.cache/pip
    - ${HOME}/.local
before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log
  - cd ${HOME} && rm -rf ${TRAVIS_BUILD_DIR}
env:
  global:
    - PATH=${HOME}/.local/bin:${PATH} # use pip user-installed binaries

install: go get -v github.com/spf13/hugo
script:
  - rm -rf public # cleanup
  - hugo -v
  - pip install --disable-pip-version-check --user s3cmd
  - s3cmd sync --delete-removed -P -M --server-side-encryption public/ s3://${BUCKET_NAME}/
notifications:
  email:
    on_failure: always
