language: go
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
    - $HOME/.cache/pip
    - $HOME/.local
install: go get -v github.com/spf13/hugo
script:
  - export PATH=${HOME}/.local/bin:${PATH} # use pip user-installed binaries
  - rm -rf public # cleanup
  - hugo -v
  - pip install --upgrade --user pip
  - pip install --user s3cmd
  - s3cmd sync --delete-removed -P -M --server-side-encryption public/ s3://${BUCKET_NAME}/
notifications:
  email:
    on_failure: always
