branches:
  only:
    - master
language: go
cache:
  directories:
    - ${GOPATH}/pkg
    - ${GOPATH}/src
    - ${HOME}/.cache/pip
    - ${HOME}/.local
before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log
  - cd ${HOME} && rm -rf ${TRAVIS_BUILD_DIR}
env:
  global:
    - PATH=${HOME}/.local/bin:${PATH} # use pip user-installed binaries

install: go get -v github.com/spf13/hugo
before_script:
  - rm -rf public # cleanup
  - pip install --disable-pip-version-check --user s3cmd Pygments
script:
  - hugo -v && s3cmd sync --delete-removed -P -M --no-mime-magic --server-side-encryption public/ s3://${BUCKET_NAME}/
notifications:
  email:
    on_failure: always
  slack:
    secure: "OcD/86Ra8GXOEOeWqMwxQBl0diOAxjGyErpo3R9nfe6hIVLZx7RXW5dWmf9EKozsDNbGfDdAQ4k9YPrv6vuOK7SbGcZqdDCuxH4ALp8iN8kqOIg7T/1Sgj83jxFWS3TV8NnIMWzSeLmN/8ETdXx+dxYd0ZPdJ9G+Q+t3malR6x51tKw8Jwx5aVlvAxzre7xSorAfhRv2jh2+pv3APjbJWl2AZw1NKrNgWowoij/gwPndYgHi27ypJ5toPMRkEvmkbmcwkGYp3R8RaYm+6egqzomcbYWDbjmB/H9Aab+/tsufaKFma7tUDEyj6um98BRA2u5C+GUglVaWKwdmPeWq8u/sCRNlIVdTm0CSANV8A0WNG4D24CyDJ1oaJ2Mie3z33gPc1DqInI7vNsgPShw/dqVWjc0dyAmDeoF/PBwheAtP6xU1cgZwhBBSjJuxszBxvnPxFZC6Hfq+22UWCOzmLY60DeEvJkELEgH4Y3SqNWom9Vru4H1ClZeO2GS0zGRgO6EHLcRk4FzfoGY9Zw4LTFolfPPkSeOP2oIGYqnViP0zR1fNHncphtmA3rWmNcINMhuFt4U/ajfOFPowofGTGpnqFYWqkhTS5dpavsrdYyBrHzq15FRgzqicEm9dtVEy9We79bBNOtXXmx/HG7chVvtbSeEI74AKQHhYMejgW5k="
